development:
  bucket: eandv-development
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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
  acl: public-read
test:
  bucket:  eandv-test
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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
production:
  bucket:  eandv
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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


