--- 
javascripts: 
- base: 
  - _jquery
  - _jrails
  - _jquery-ui
  - swfobject
  - application
- secondary:
  - eye
  - utils
  - ui.tabs
  - ui.combobox
  - spacegallery
  - jquery.easing.1.3
  - sexylightbox.v2.3.jquery
  - reflection
  - jScrollPane
  - jquery.tmpl.1.1.1
  - jquery.mousewheel
  - jquery.jcarousel
  - browserdetect
- admin:
  - _jquery
  - _jrails
  - _jquery-ui
  - swfobject
  - application  
  - eye
  - utils
  - ui.tabs
  - ui.combobox
  - spacegallery
  - jquery.easing.1.3
  - sexylightbox.v2.3.jquery
  - reflection
  - jScrollPane
  - jquery.tmpl.1.1.1
  - jquery.mousewheel
  - jquery.jcarousel
  - browserdetect
  - jquery.Jcrop
  
stylesheets: 
- base: 
  - envnpb_front
  - left-side
  - right-side
  - sexylightbox
  - ui.combobox
  - ui.tabs
  - jquery.jcarousel
  - JScrollPane
- secondary:
  - sexylightbox
  - ui.combobox
  - ui.tabs
  - jquery.jcarousel
  - JScrollPane

  
