development:
  bucket: eandv_npb_development
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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

test:
  bucket: eandv_npb_test
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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

production:
  bucket: eandv_npb
  access_key_id: AKIAI7DG2I3UGHEC6FKA
  secret_access_key: 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
